name: link_target
description: "Adds hyperlink preview behaviour on hover found on browsers."
version: 0.0.1
homepage: https://github.com/juliotati/link_target

issue_tracker: https://github.com/juliotati/link_targetissues
topics:
  - web
  - hyperlink
  - link-preview

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
