name: link_target
description: "Adds hyperlink glance behaviour on hover found on the bottom left of the browser page."
version: 0.1.1
homepage: https://github.com/juliotati/link_target

issue_tracker: https://github.com/juliotati/link_target/issues
topics:
  - web
  - hyperlink
  - link-preview
  - link-glance

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
