name: Tests Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  analyze-and-test:
    runs-on: macos-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v4

      - name: setup-jdk
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'
          cache-key: 'flutter-macos-stable-3.24.0-x64'
          cache-path: '${{ runner.tool_cache }}/flutter-macos-stable-3.24.0-x64-hash'
          pub-cache-key: 'flutter-pub-macos-stable-3.24.0-x64-hash'
          pub-cache-path: '${{ runner.tool_cache }}/flutter/stable-3.24.0-x64'
          flutter-version: '3.24.0'

      - name: load-dependencies
        run: dart pub get

      - name: analyse-link_target
        run: dart analyze --fatal-warnings

      - name: analyse-example
        run: dart analyze example --fatal-warnings

      - name: validate-format
        run: dart format --line-length 80 --set-exit-if-changed .

      - name: run-tests
        run: flutter test
